package com.c0d3engr.onlineshop.model.entity;

import java.sql.Timestamp;

import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Builder
@Data
@Entity (name = "cart_items")
public class Cart_items_entity {
    @Id
    @Autogeneratedvalue
    private Integer id;
    private Integer session_id;
    private Integer product_id;
    private Integer quantity;
    private Timestamp created_at;
    private Timestamp modified_at;
}
